const DEFAULT = {
  theme:{font:'Inter',accent:'#f5b51b',bg:'#071018',panel:'#0c1721',text:'#f5f7f8',heroImage:''},
  hero:{eyebrow:'CIVIL ENGINEER',name:'PATTARAPON POLADECH',tagline:'Building better infrastructure for a more connected tomorrow.',location:'Bangkok, Thailand',email:'pattarapon.p@gmail.com',cv:'#',linkedin:'#'},
  about:{title:'Turning Plans into Real-World Impact',body:'Civil Engineering graduate with hands-on experience as a Tunnel Engineer Intern. Interested in tunnel engineering, construction planning, scheduling, and practical productivity improvement.',cards:[['Tunnel Engineering','TBM / Underground Works'],['Construction Planning','Scheduling / Workflow'],['Problem Solving','Operational Analysis'],['Continuous Learning','Tools / Technology']]},
  projects:[
    {num:'01',title:'Tunnel Excavation & Locomotive Cycle Scheduling',desc:'Construction planning workflow for TBM excavation, spoil haulage, assembly, and locomotive cycle optimization.',tags:['Primavera P6','TBM','Excel / VBA'],link:'#'},
    {num:'02',title:'MOC Mortar with Fly Ash & Water Hyacinth Fiber',desc:'Experimental study covering mix design, tensile testing, curing ages, and material performance.',tags:['Materials','Mix Design','Testing'],link:'#'},
    {num:'03',title:'GIS-MCDA for Urban Planning',desc:'Spatial decision framework for identifying and classifying priority areas using multi-criteria analysis.',tags:['GIS','MCDA','Urban Planning'],link:'#'},
    {num:'04',title:'Engineering Data & Automation Tools',desc:'Excel/VBA tools for importing data, generating engineering charts, and visualizing project information.',tags:['Excel','VBA','Automation'],link:'#'}
  ],
  experience:{company:'Ch. Karnchang Public Co., Ltd.',role:'Tunnel Engineer Intern',period:'2023',bullets:['Supported construction planning and scheduling for a TBM tunnel project.','Assisted in tracking excavation progress and locomotive cycles.','Prepared site data, reports, and coordination materials.','Used Primavera P6 and Excel for schedule analysis and visualization.']},
  skills:[['Tunnel Engineering','TBM, underground construction'],['Construction Planning','Scheduling, workflow design'],['Primavera P6','CPM, progress tracking'],['Excel / VBA','Engineering automation'],['GIS','Spatial analysis, MCDA'],['Python','Data analysis / visualization']],
  contact:{title:"Let's Build Something Together",text:'Open to engineering, planning, infrastructure, and construction opportunities.',email:'pattarapon.p@gmail.com',linkedin:'#'}
};

let state = JSON.parse(localStorage.getItem('civilPortfolio')||'null') || structuredClone(DEFAULT);
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function save(){localStorage.setItem('civilPortfolio',JSON.stringify(state)); applyTheme(); render(); toast('Saved locally.');}
function reset(){if(confirm('Reset the portfolio to the original template?')){state=structuredClone(DEFAULT);save()}}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
function applyTheme(){const r=document.documentElement;r.style.setProperty('--font',state.theme.font==='Space Grotesk'?'"Space Grotesk",sans-serif':'Inter,system-ui,sans-serif');r.style.setProperty('--accent',state.theme.accent);r.style.setProperty('--bg',state.theme.bg);r.style.setProperty('--panel',state.theme.panel);r.style.setProperty('--text',state.theme.text);}
function render(){document.title=state.hero.name+' — Civil Engineering Portfolio';$('#site').innerHTML=`
<nav class="nav"><div class="container nav-inner"><a class="brand" href="#home"><span class="brand-mark">CE</span><span>${esc(state.hero.name)}</span></a><div class="nav-links"><a href="#about">About</a><a href="#projects">Projects</a><a href="#experience">Experience</a><a href="#skills">Skills</a><a href="#contact">Contact</a></div><button class="admin-toggle" onclick="openAdmin()">Edit Website</button></div></nav>
<section id="home" class="hero" style="background-image:linear-gradient(90deg,rgba(7,16,24,.98) 0%,rgba(7,16,24,.9) 38%,rgba(7,16,24,.28) 100%)${state.theme.heroImage?`,url('${state.theme.heroImage}')`:''};background-position:center;background-size:cover"><div class="container hero-grid"><div><div class="eyebrow">${esc(state.hero.eyebrow)}</div><h1>${esc(state.hero.name).replace(' ',' <span>')}</h1><p class="hero-copy">${esc(state.hero.tagline)}</p><div class="actions"><a class="btn primary" href="#projects">View Projects →</a><a class="btn" href="${esc(state.hero.cv)}" target="_blank">↓ Download CV</a></div><p style="color:#81929d;font-size:12px;margin-top:25px">⌖ ${esc(state.hero.location)} &nbsp; · &nbsp; ✉ ${esc(state.hero.email)} &nbsp; · &nbsp; in LinkedIn</p></div><div class="hero-visual"><div class="tunnel"><div class="rail"></div><div class="machine"></div></div></div></div></section>
<section id="about" class="section"><div class="container"><div class="section-header"><div><div class="kicker">01 · ABOUT ME</div><h2>${esc(state.about.title)}</h2></div><div class="section-sub">${esc(state.about.body)}</div></div><div class="about-grid"><div class="panel"><div class="eyebrow" style="margin:0 0 8px">ENGINEERING MINDSET</div><p style="font-size:20px;margin:0;color:#dce3e7">I like turning construction information into clear workflows, schedules, and decisions that can be used on real projects.</p></div><div class="fact-grid">${state.about.cards.map(c=>`<div class="fact"><strong>${esc(c[0])}</strong><span>${esc(c[1])}</span></div>`).join('')}</div></div></div></section>
<section id="projects" class="section" style="background:#08131b;border-top:1px solid var(--line);border-bottom:1px solid var(--line)"><div class="container"><div class="section-header"><div><div class="kicker">02 · SELECTED WORK</div><h2>Featured Projects</h2></div><div class="section-sub">Projects are presented as engineering case studies: problem → method → output → result.</div></div><div class="project-list">${state.projects.map(p=>`<a class="project-card" href="${esc(p.link)}"><div class="project-num">${esc(p.num)}</div><div class="mini">CASE STUDY</div><h3>${esc(p.title)}</h3><div class="mini">${esc(p.desc)}</div><div class="tags" style="margin-top:16px">${p.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></a>`).join('')}</div></div></section>
<section id="experience" class="section"><div class="container"><div class="section-header"><div><div class="kicker">03 · EXPERIENCE</div><h2>Work Experience</h2></div></div><div class="experience"><div class="panel"><div class="year">${esc(state.experience.period)}</div><h3>${esc(state.experience.company)}</h3><p style="color:#d6dee2">${esc(state.experience.role)}</p></div><div class="panel">${state.experience.bullets.map((b,i)=>`<div class="timeline-item"><div class="year">0${i+1}</div><p>${esc(b)}</p></div>`).join('')}</div></div></div></section>
<section id="skills" class="section" style="background:#08131b;border-top:1px solid var(--line);border-bottom:1px solid var(--line)"><div class="container"><div class="section-header"><div><div class="kicker">04 · CAPABILITIES</div><h2>Technical Skills</h2></div></div><div class="skills">${state.skills.map(s=>`<div class="skill"><b>${esc(s[0])}</b><span>${esc(s[1])}</span></div>`).join('')}</div></div></section>
<section id="contact" class="section contact"><div class="container contact-grid"><div><div class="kicker">05 · CONTACT</div><h2 style="font-size:46px;margin:10px 0">${esc(state.contact.title)}</h2><p style="color:#a1afb7;max-width:540px">${esc(state.contact.text)}</p></div><div class="panel"><p style="margin-top:0;color:#93a2aa">Email</p><a href="mailto:${esc(state.contact.email)}" style="font-size:18px;font-weight:700">${esc(state.contact.email)}</a><div class="actions"><a class="btn primary" href="${esc(state.contact.linkedin)}" target="_blank">LinkedIn ↗</a><a class="btn" href="mailto:${esc(state.contact.email)}">Email Me</a></div></div></div></section>
<footer class="container footer"><span>© ${new Date().getFullYear()} ${esc(state.hero.name)}</span><span>Civil Engineering · Tunnel · Planning</span></footer>`}
function openAdmin(){buildAdmin();$('.admin-panel').classList.add('open')};function closeAdmin(){$('.admin-panel').classList.remove('open')}
function buildAdmin(){let p=document.createElement('div');p.className='admin-panel open';p.innerHTML=`<aside class="admin-shell"><div class="admin-head"><div><div class="admin-title">Portfolio Editor</div><div style="font-size:11px;color:#83939e">Visual settings · content · links</div></div><button class="small-btn" onclick="closeAdmin();this.closest('.admin-panel').remove()">Close</button></div><div class="admin-body">
<details class="admin-block" open><summary>Site style</summary><div class="admin-content"><div class="field"><label>Font</label><select id="font"><option ${state.theme.font==='Inter'?'selected':''}>Inter</option><option ${state.theme.font==='Space Grotesk'?'selected':''}>Space Grotesk</option></select></div><div class="row"><div class="field"><label>Accent</label><input id="accent" type="color" value="${esc(state.theme.accent)}"></div><div class="field"><label>Background</label><input id="bg" type="color" value="${esc(state.theme.bg)}"></div></div><div class="field"><label>Hero background image</label><input id="heroImage" placeholder="Paste image URL" value="${esc(state.theme.heroImage)}"><small style="color:#778995">For a real deployment, upload images to Storage rather than storing giant files in the browser.</small></div></div></details>
<details class="admin-block" open><summary>Hero</summary><div class="admin-content"><div class="field"><label>Name</label><input id="name" value="${esc(state.hero.name)}"></div><div class="field"><label>Eyebrow</label><input id="eyebrow" value="${esc(state.hero.eyebrow)}"></div><div class="field"><label>Tagline</label><textarea id="tagline">${esc(state.hero.tagline)}</textarea></div><div class="row"><div class="field"><label>Email</label><input id="email" value="${esc(state.hero.email)}"></div><div class="field"><label>Location</label><input id="location" value="${esc(state.hero.location)}"></div></div><div class="row"><div class="field"><label>CV link</label><input id="cv" value="${esc(state.hero.cv)}"></div><div class="field"><label>LinkedIn</label><input id="linkedin" value="${esc(state.hero.linkedin)}"></div></div></div></details>
<details class="admin-block"><summary>About</summary><div class="admin-content"><div class="field"><label>Title</label><input id="aboutTitle" value="${esc(state.about.title)}"></div><div class="field"><label>Body</label><textarea id="aboutBody">${esc(state.about.body)}</textarea></div></div></details>
<details class="admin-block"><summary>Projects</summary><div class="admin-content" id="projectsEditor">${state.projects.map((p,i)=>`<div class="panel" style="padding:14px;margin-bottom:10px"><div class="row"><input data-p="num" data-i="${i}" value="${esc(p.num)}"><input data-p="title" data-i="${i}" value="${esc(p.title)}"></div><div class="field"><label>Description</label><textarea data-p="desc" data-i="${i}">${esc(p.desc)}</textarea></div><div class="field"><label>Tags (comma separated)</label><input data-p="tags" data-i="${i}" value="${esc(p.tags.join(', '))}"></div><div class="field"><label>Button / card link</label><input data-p="link" data-i="${i}" value="${esc(p.link)}"></div><button class="small-btn" onclick="removeProject(${i})">Remove project</button></div>`).join('')}<div class="admin-actions"><button class="small-btn primary" onclick="addProject()">+ Add project</button></div></div></details>
<details class="admin-block"><summary>Experience</summary><div class="admin-content"><div class="row"><div class="field"><label>Company</label><input id="company" value="${esc(state.experience.company)}"></div><div class="field"><label>Role</label><input id="role" value="${esc(state.experience.role)}"></div></div><div class="field"><label>Period</label><input id="period" value="${esc(state.experience.period)}"></div><div class="field"><label>Bullets (one per line)</label><textarea id="bullets">${esc(state.experience.bullets.join('\n'))}</textarea></div></div></details>
<details class="admin-block"><summary>Skills</summary><div class="admin-content">${state.skills.map((s,i)=>`<div class="row" style="margin-bottom:8px"><input data-s="0" data-i="${i}" value="${esc(s[0])}"><input data-s="1" data-i="${i}" value="${esc(s[1])}"></div>`).join('')}</div></details>
<details class="admin-block"><summary>Contact</summary><div class="admin-content"><div class="field"><label>Title</label><input id="contactTitle" value="${esc(state.contact.title)}"></div><div class="field"><label>Text</label><textarea id="contactText">${esc(state.contact.text)}</textarea></div><div class="row"><div class="field"><label>Email</label><input id="contactEmail" value="${esc(state.contact.email)}"></div><div class="field"><label>LinkedIn</label><input id="contactLinkedin" value="${esc(state.contact.linkedin)}"></div></div></div></details>
<div class="admin-actions"><button class="small-btn primary" onclick="saveAdmin()">Save changes</button><button class="small-btn" onclick="reset()">Reset template</button><button class="small-btn" onclick="exportJSON()">Export content JSON</button></div><p style="font-size:11px;color:#70818c;line-height:1.6">Prototype note: this editor stores content in browser localStorage. A production version should connect the same editor to authenticated Admin + Database + Image Storage.</p></div></aside>`;document.body.appendChild(p)}
function val(id){return $('#'+id)?.value??''}
function syncAdmin(){state.theme.font=val('font');state.theme.accent=val('accent')||state.theme.accent;state.theme.bg=val('bg')||state.theme.bg;state.theme.heroImage=val('heroImage');state.hero={...state.hero,name:val('name'),eyebrow:val('eyebrow'),tagline:val('tagline'),email:val('email'),location:val('location'),cv:val('cv'),linkedin:val('linkedin')};state.about.title=val('aboutTitle');state.about.body=val('aboutBody');state.experience={company:val('company'),role:val('role'),period:val('period'),bullets:val('bullets').split('\n').filter(Boolean)};state.contact={title:val('contactTitle'),text:val('contactText'),email:val('contactEmail'),linkedin:val('contactLinkedin')};document.querySelectorAll('[data-p]').forEach(el=>{const i=+el.dataset.i,k=el.dataset.p;if(k==='tags')state.projects[i][k]=el.value.split(',').map(x=>x.trim()).filter(Boolean);else state.projects[i][k]=el.value});document.querySelectorAll('[data-s]').forEach(el=>{state.skills[+el.dataset.i][+el.dataset.s]=el.value})}
function saveAdmin(){syncAdmin();localStorage.setItem('civilPortfolio',JSON.stringify(state));applyTheme();closeAdmin();document.querySelector('.admin-panel')?.remove();render();toast('Changes saved.');}
function addProject(){syncAdmin();state.projects.push({num:String(state.projects.length+1).padStart(2,'0'),title:'New Engineering Project',desc:'Describe the problem, method, output, and result.',tags:['Engineering'],link:'#'});openAdmin();toast('Project added.');}
function removeProject(i){syncAdmin();state.projects.splice(i,1);saveAdmin()}
function exportJSON(){syncAdmin();const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='portfolio-content.json';a.click();URL.revokeObjectURL(a.href);toast('JSON exported.');}
applyTheme();render();
